#!/bin/bash
# generate_genesis.sh - Helper script for OpenSY genesis block generation
#
# Copyright (c) 2025 The OpenSY developers
# Distributed under the MIT software license
#
# This script guides you through generating a new genesis block for OpenSY.
# Genesis block uses SHA256d (not RandomX), so standard Bitcoin genesis mining applies.

set -euo pipefail

echo "════════════════════════════════════════════════════════════════════════════════"
echo "                    OpenSY Genesis Block Generation Guide"
echo "════════════════════════════════════════════════════════════════════════════════"
echo ""
echo "  🇸🇾 Genesis commemorates December 8, 2024 - Syria's Liberation Day"
echo "     The fall of the Assad regime after nearly 14 years of civil war."
echo ""
echo "════════════════════════════════════════════════════════════════════════════════"
echo ""

# Fixed historical timestamp for Syria Liberation
GENESIS_TIMESTAMP=1733638680  # Dec 8, 2024 06:18:00 UTC
GENESIS_DATE="December 8, 2024 at 06:18:00 UTC"
GENESIS_MESSAGE="Dec 8 2024 - Syria Liberated from Assad / سوريا حرة"

echo "GENESIS PARAMETERS (Fixed - Historical)"
echo "───────────────────────────────────────"
echo "  Timestamp:  $GENESIS_TIMESTAMP"
echo "  Date:       $GENESIS_DATE"
echo "  Message:    \"$GENESIS_MESSAGE\""
echo "  Reward:     10,000 SYL"
echo "  Difficulty: 0x1e00ffff (minimum)"
echo "  Algorithm:  SHA256d (genesis only; RandomX from block 1)"
echo ""

echo "WHY RE-GENESIS IS NEEDED"
echo "───────────────────────────────────────"
echo "  Blocks 64-3049 have invalid RandomX proof-of-work hashes."
echo "  Root cause: Rapid development (Dec 9-11) with validation gaps."
echo ""
echo "  ✅ Blocks 0-63 were valid"
echo "  ❌ Block 64+ failed validation after fixes were applied"
echo "  ✅ Current code is correct - validation works properly now"
echo ""

echo "STEP 1: Build OpenSY with Updated Chainparams"
echo "───────────────────────────────────────"
echo "  The timestamp has already been updated to $GENESIS_TIMESTAMP."
echo "  Build the project:"
echo ""
echo "    cd /Users/hamoudi/OpenSyria/build"
echo "    cmake .."
echo "    make -j\$(sysctl -n hw.ncpu)"
echo ""

echo "STEP 2: Mine the Genesis Block"
echo "───────────────────────────────────────"
echo "  Genesis uses SHA256d, so use the grind utility:"
echo ""
echo "    # Method 1: Using grind-sha256d (if available)"
echo "    ./bin/opensy-util grind 0"
echo ""
echo "    # Method 2: Use mine_genesis.cpp"
echo "    cd /Users/hamoudi/OpenSyria"
echo "    ./mine_genesis.sh  # or compile and run mine_genesis.cpp"
echo ""
echo "  The miner will output a valid nonce. Example output:"
echo "    Found valid nonce: 2389547"
echo "    Genesis hash: 00000005a2b3c4d5..."
echo ""

echo "STEP 3: Update chainparams.cpp with Mined Values"
echo "───────────────────────────────────────"
echo "  Edit src/kernel/chainparams.cpp with the mined nonce and hash:"
echo ""
echo "    genesis = CreateGenesisBlock(1733638680, MINED_NONCE, 0x1e00ffff, 1, 10000 * COIN);"
echo "    consensus.hashGenesisBlock = genesis.GetHash();"
echo "    assert(consensus.hashGenesisBlock == uint256{\"MINED_HASH\"});"
echo "    assert(genesis.hashMerkleRoot == uint256{\"MERKLE_ROOT\"});"
echo ""

echo "STEP 4: Verify Merkle Root"
echo "───────────────────────────────────────"
echo "  Merkle root depends only on the coinbase transaction, which includes:"
echo "    - Timestamp message: \"$GENESIS_MESSAGE\""
echo "    - Reward: 10,000 SYL"
echo "    - Output script: P2PK to known unspendable key"
echo ""
echo "  Compute with:"
echo "    genesis.hashMerkleRoot = BlockMerkleRoot(genesis);"
echo ""

echo "STEP 5: Rebuild and Test"
echo "───────────────────────────────────────"
echo "    cd build && make -j\$(sysctl -n hw.ncpu)"
echo ""
echo "    # Start node (should accept genesis and wait for blocks)"
echo "    ./bin/opensyd -printtoconsole 2>&1 | head -100"
echo ""
echo "    # Check genesis block"
echo "    ./bin/opensy-cli getblockhash 0"
echo "    ./bin/opensy-cli getblock \$(./bin/opensy-cli getblockhash 0)"
echo ""

echo "STEP 6: Clear Old Chain Data"
echo "───────────────────────────────────────"
echo "  ⚠️  IMPORTANT: Remove all old chain data before starting!"
echo ""
echo "    rm -rf ~/.opensy/blocks"
echo "    rm -rf ~/.opensy/chainstate"
echo "    rm -f ~/.opensy/peers.dat"
echo "    rm -f ~/.opensy/banlist.json"
echo ""

echo "STEP 7: Start Mining Fresh Chain"
echo "───────────────────────────────────────"
echo "  After genesis is set, mine block 1+ with RandomX:"
echo ""
echo "    # Generate mining address"
echo "    ./bin/opensy-cli getnewaddress \"mining\""
echo ""
echo "    # Start mining"
echo "    ./bin/opensy-cli generatetoaddress 1 <YOUR_ADDRESS>"
echo ""
echo "  Block 1 will use RandomX (CPU-friendly, ASIC-resistant)!"
echo ""

echo "════════════════════════════════════════════════════════════════════════════════"
echo "  🎉 OpenSY - Free currency for a free Syria"
echo "════════════════════════════════════════════════════════════════════════════════"
